services:
  postgres:
    container_name: lol-postgres
    build:
      context: ./db
    image: lol-custom-postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  pgadmin:
    container_name: lol-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME}
    external: true
