CREATE TABLE matches (
    game_id BIGINT PRIMARY KEY,
    game_start_timestamp TIMESTAMPTZ NOT NULL,
    -- queue_id SMALLINT,
    game_duration SMALLINT,
    match_id TEXT REFERENCES match_ids(match_id),
    platform_name TEXT NOT NULL,
    -- game_mode TEXT,
    game_version TEXT,
    end_of_game_result TEXT NOT NULL,
    FOREIGN KEY (platform_name) REFERENCES platforms(platform_name)
);

CREATE TYPE team_position_enum AS ENUM ('TOP', 'JUNGLE', 'MIDDLE', 'BOTTOM', 'UTILITY');

CREATE TABLE match_participants (
    game_id BIGINT NOT NULL,
    team_position team_position_enum NOT NULL,
    participant_id SMALLINT NOT NULL,
    champion_id SMALLINT NOT NULL,
    puuid TEXT NOT NULL REFERENCES users(puuid),
    PRIMARY KEY (game_id, participant_id),
    FOREIGN KEY (game_id) REFERENCES matches(game_id) ON DELETE CASCADE
);

CREATE TYPE team_enum AS ENUM ('BLUE', 'RED');

CREATE TABLE teams (
    game_id BIGINT NOT NULL,
    team_id team_enum NOT NULL,
    epic_monster_state SMALLINT NOT NULL DEFAULT 0,
    first_blood_state SMALLINT NOT NULL DEFAULT 0,
    first_turret_state SMALLINT NOT NULL DEFAULT 0,
    atakhan_kills SMALLINT NOT NULL DEFAULT 0,
    baron_kills SMALLINT NOT NULL DEFAULT 0,
    champion_kills SMALLINT NOT NULL DEFAULT 0,
    dragon_kills SMALLINT NOT NULL DEFAULT 0,
    horde_kills SMALLINT NOT NULL DEFAULT 0,
    inhibitor_kills SMALLINT NOT NULL DEFAULT 0,
    rift_herald_kills SMALLINT NOT NULL DEFAULT 0,
    tower_kills SMALLINT NOT NULL DEFAULT 0,
    win BOOLEAN NOT NULL DEFAULT FALSE,
    atakhan_first BOOLEAN NOT NULL DEFAULT FALSE,
    baron_first BOOLEAN NOT NULL DEFAULT FALSE,
    champion_first BOOLEAN NOT NULL DEFAULT FALSE,
    dragon_first BOOLEAN NOT NULL DEFAULT FALSE,
    horde_first BOOLEAN NOT NULL DEFAULT FALSE,
    inhibitor_first BOOLEAN NOT NULL DEFAULT FALSE,
    rift_herald_first BOOLEAN NOT NULL DEFAULT FALSE,
    tower_first BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (game_id, team_id),
    FOREIGN KEY (game_id) REFERENCES matches(game_id) ON DELETE CASCADE
);

CREATE TABLE team_bans (
    game_id BIGINT NOT NULL,
    team_id team_enum NOT NULL,
    pick_turn SMALLINT NOT NULL,
    champion_id SMALLINT NOT NULL,
    PRIMARY KEY (game_id, team_id, pick_turn),
    FOREIGN KEY (game_id, team_id) REFERENCES teams (game_id, team_id) ON DELETE CASCADE
);

CREATE TABLE participant_stats (
    game_id BIGINT NOT NULL,
    champ_experience INT NOT NULL DEFAULT 0,
    damage_dealt_to_buildings INT NOT NULL DEFAULT 0,
    damage_dealt_to_objectives INT NOT NULL DEFAULT 0,
    damage_dealt_to_turrets INT NOT NULL DEFAULT 0,
    damage_self_mitigated INT NOT NULL DEFAULT 0,
    largest_critical_strike INT NOT NULL DEFAULT 0,
    magic_damage_dealt INT NOT NULL DEFAULT 0,
    magic_damage_dealt_to_champions INT NOT NULL DEFAULT 0,
    magic_damage_taken INT NOT NULL DEFAULT 0,
    physical_damage_dealt INT NOT NULL DEFAULT 0,
    physical_damage_dealt_to_champions INT NOT NULL DEFAULT 0,
    physical_damage_taken INT NOT NULL DEFAULT 0,
    total_damage_dealt INT NOT NULL DEFAULT 0,
    total_damage_dealt_to_champions INT NOT NULL DEFAULT 0,
    total_damage_shielded_on_teammates INT NOT NULL DEFAULT 0,
    total_damage_taken INT NOT NULL DEFAULT 0,
    true_damage_dealt INT NOT NULL DEFAULT 0,
    true_damage_dealt_to_champions INT NOT NULL DEFAULT 0,
    true_damage_taken INT NOT NULL DEFAULT 0,
    time_ccing_others INT NOT NULL DEFAULT 0,
    total_time_cc_dealt INT NOT NULL DEFAULT 0,
    total_heal INT NOT NULL DEFAULT 0,
    total_heals_on_teammates INT NOT NULL DEFAULT 0,
    total_units_healed INT NOT NULL DEFAULT 0,
    gold_earned INT NOT NULL DEFAULT 0,
    gold_spent INT NOT NULL DEFAULT 0,
    participant_id SMALLINT NOT NULL,
    champion_transform SMALLINT NOT NULL DEFAULT 0,
    champ_level SMALLINT NOT NULL DEFAULT 0,
    kills SMALLINT NOT NULL DEFAULT 0,
    killing_sprees SMALLINT NOT NULL DEFAULT 0,
    largest_killing_spree SMALLINT NOT NULL DEFAULT 0,
    double_kills SMALLINT NOT NULL DEFAULT 0,
    triple_kills SMALLINT NOT NULL DEFAULT 0,
    quadra_kills SMALLINT NOT NULL DEFAULT 0,
    penta_kills SMALLINT NOT NULL DEFAULT 0,
    largest_multi_kill SMALLINT NOT NULL DEFAULT 0,
    bounty_level SMALLINT NOT NULL DEFAULT 0,
    deaths SMALLINT NOT NULL DEFAULT 0,
    longest_time_spent_living SMALLINT NOT NULL DEFAULT 0,
    total_time_spent_dead SMALLINT NOT NULL DEFAULT 0,
    assists SMALLINT NOT NULL DEFAULT 0,
    spell1_casts SMALLINT NOT NULL DEFAULT 0,
    spell2_casts SMALLINT NOT NULL DEFAULT 0,
    spell3_casts SMALLINT NOT NULL DEFAULT 0,
    spell4_casts SMALLINT NOT NULL DEFAULT 0,
    summoner1_casts SMALLINT NOT NULL DEFAULT 0,
    summoner1_id SMALLINT NOT NULL DEFAULT 0,
    summoner2_casts SMALLINT NOT NULL DEFAULT 0,
    summoner2_id SMALLINT NOT NULL DEFAULT 0,
    detector_wards_placed SMALLINT NOT NULL DEFAULT 0,
    wards_placed SMALLINT NOT NULL DEFAULT 0,
    wards_killed SMALLINT NOT NULL DEFAULT 0,
    vision_score SMALLINT NOT NULL DEFAULT 0,
    inhibitor_kills SMALLINT NOT NULL DEFAULT 0,
    inhibitor_takedowns SMALLINT NOT NULL DEFAULT 0,
    inhibitors_lost SMALLINT NOT NULL DEFAULT 0,
    turrets_lost SMALLINT NOT NULL DEFAULT 0,
    turret_takedowns SMALLINT NOT NULL DEFAULT 0,
    turret_kills SMALLINT NOT NULL DEFAULT 0,
    all_in_pings SMALLINT NOT NULL DEFAULT 0,
    assist_me_pings SMALLINT NOT NULL DEFAULT 0,
    command_pings SMALLINT NOT NULL DEFAULT 0,
    enemy_missing_pings SMALLINT NOT NULL DEFAULT 0,
    enemy_vision_pings SMALLINT NOT NULL DEFAULT 0,
    hold_pings SMALLINT NOT NULL DEFAULT 0,
    get_back_pings SMALLINT NOT NULL DEFAULT 0,
    need_vision_pings SMALLINT NOT NULL DEFAULT 0,
    on_my_way_pings SMALLINT NOT NULL DEFAULT 0,
    push_pings SMALLINT NOT NULL DEFAULT 0,
    vision_cleared_pings SMALLINT NOT NULL DEFAULT 0,
    dragon_kills SMALLINT NOT NULL DEFAULT 0,
    baron_kills SMALLINT NOT NULL DEFAULT 0,
    objectives_stolen SMALLINT NOT NULL DEFAULT 0,
    objectives_stolen_assists SMALLINT NOT NULL DEFAULT 0,
    total_ally_jungle_minions_killed SMALLINT NOT NULL DEFAULT 0,
    total_enemy_jungle_minions_killed SMALLINT NOT NULL DEFAULT 0,
    neutral_minions_killed SMALLINT NOT NULL DEFAULT 0,
    total_minions_killed SMALLINT NOT NULL DEFAULT 0,
    consumables_purchased SMALLINT NOT NULL DEFAULT 0,
    game_ended_in_surrender BOOLEAN NOT NULL DEFAULT FALSE,
    win BOOLEAN NOT NULL DEFAULT FALSE,
    first_blood_kill BOOLEAN NOT NULL DEFAULT FALSE,
    first_blood_assist BOOLEAN NOT NULL DEFAULT FALSE,
    first_tower_kill BOOLEAN NOT NULL DEFAULT FALSE,
    first_tower_assist BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (game_id, participant_id),
    FOREIGN KEY (game_id, participant_id) REFERENCES match_participants (game_id, participant_id) ON DELETE CASCADE
);

CREATE TABLE challenges (
    game_id BIGINT NOT NULL,
    bounty_gold INT NOT NULL DEFAULT 0,
    effective_heal_and_shielding INT NOT NULL DEFAULT 0,
    kda REAL NOT NULL DEFAULT 0,
    kill_participation REAL NOT NULL DEFAULT 0,
    damage_per_minute REAL NOT NULL DEFAULT 0,
    damage_taken_on_team_pct REAL NOT NULL DEFAULT 0,
    team_damage_pct REAL NOT NULL DEFAULT 0,
    control_ward_time_coverage_in_river_or_enemy_half REAL NOT NULL DEFAULT 0,
    vision_score_advantage_lane_opponent REAL NOT NULL DEFAULT 0,
    vision_score_per_minute REAL NOT NULL DEFAULT 0,
    more_enemy_jungle_than_opponent REAL NOT NULL DEFAULT 0,
    gold_per_minute REAL NOT NULL DEFAULT 0,
    participant_id SMALLINT NOT NULL,
    max_level_lead_lane_opponent SMALLINT NOT NULL DEFAULT 0,
    jungler_kills_early_jungle SMALLINT NOT NULL DEFAULT 0,
    kills_on_laners_early_jungle_as_jungler SMALLINT NOT NULL DEFAULT 0,
    takedowns_first_25_minutes SMALLINT NOT NULL DEFAULT 0,
    aces_before_15_minutes SMALLINT NOT NULL DEFAULT 0,
    buffs_stolen SMALLINT NOT NULL DEFAULT 0,
    dodge_skill_shots_small_window SMALLINT NOT NULL DEFAULT 0,
    flawless_ace SMALLINT NOT NULL DEFAULT 0,
    kill_after_hidden_with_ally SMALLINT NOT NULL DEFAULT 0,
    kills_near_enemy_turret SMALLINT NOT NULL DEFAULT 0,
    kills_on_other_lanes_early_jungle_as_laner SMALLINT NOT NULL DEFAULT 0,
    kills_under_own_turret SMALLINT NOT NULL DEFAULT 0,
    kills_with_help_from_epic_monster SMALLINT NOT NULL DEFAULT 0,
    multikills_after_aggressive_flash SMALLINT NOT NULL DEFAULT 0,
    took_large_damage_survived SMALLINT NOT NULL DEFAULT 0,
    takedowns_before_jungle_minion_spawn SMALLINT NOT NULL DEFAULT 0,
    takedowns_after_gaining_level_advantage SMALLINT NOT NULL DEFAULT 0,
    takedown_on_first_turret SMALLINT NOT NULL DEFAULT 0,
    solo_kills SMALLINT NOT NULL DEFAULT 0,
    skillshots_dodged SMALLINT NOT NULL DEFAULT 0,
    save_ally_from_death SMALLINT NOT NULL DEFAULT 0,
    quick_solo_kills SMALLINT NOT NULL DEFAULT 0,
    pick_kill_with_ally SMALLINT NOT NULL DEFAULT 0,
    outnumbered_kills SMALLINT NOT NULL DEFAULT 0,
    enemy_champion_immobilization SMALLINT NOT NULL DEFAULT 0,
    immobilize_and_kill_with_ally SMALLINT NOT NULL DEFAULT 0,
    knock_enemy_into_team_and_kill SMALLINT NOT NULL DEFAULT 0,
    land_skill_shots_early_game SMALLINT NOT NULL DEFAULT 0,
    skillshots_hit SMALLINT NOT NULL DEFAULT 0,
    ward_takedowns_before_20m SMALLINT NOT NULL DEFAULT 0,
    ward_takedowns SMALLINT NOT NULL DEFAULT 0,
    wards_guarded SMALLINT NOT NULL DEFAULT 0,
    solo_turret_late_game SMALLINT NOT NULL DEFAULT 0,
    k_turrets_destroyed_before_plates_fall SMALLINT NOT NULL DEFAULT 0,
    turrets_taken_with_rift_herald SMALLINT NOT NULL DEFAULT 0,
    turret_plates_taken SMALLINT NOT NULL DEFAULT 0,
    quick_first_turret SMALLINT NOT NULL DEFAULT 0,
    multi_turret_rift_herald_count SMALLINT NOT NULL DEFAULT 0,
    max_cs_advantage_on_lane_opponent SMALLINT NOT NULL DEFAULT 0,
    void_monster_kill SMALLINT NOT NULL DEFAULT 0,
    allied_jungle_monster_kills SMALLINT NOT NULL DEFAULT 0,
    elder_dragon_kills_with_opposing_soul SMALLINT NOT NULL DEFAULT 0,
    enemy_jungle_monster_kills SMALLINT NOT NULL DEFAULT 0,
    epic_monster_steals SMALLINT NOT NULL DEFAULT 0,
    initial_buff_count SMALLINT NOT NULL DEFAULT 0,
    initial_crab_count SMALLINT NOT NULL DEFAULT 0,
    jungle_cs_before_10_minutes SMALLINT NOT NULL DEFAULT 0,
    lane_minions_first_10_minutes SMALLINT NOT NULL DEFAULT 0,
    rift_herald_takedowns SMALLINT NOT NULL DEFAULT 0,
    solo_baron_kills SMALLINT NOT NULL DEFAULT 0,
    team_rift_herald_kills SMALLINT NOT NULL DEFAULT 0,
    team_elder_dragon_kills SMALLINT NOT NULL DEFAULT 0,
    perfect_dragon_souls_taken SMALLINT NOT NULL DEFAULT 0,
    had_afk_teammate BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (game_id, participant_id),
    FOREIGN KEY (game_id, participant_id) REFERENCES match_participants (game_id, participant_id) ON DELETE CASCADE
);