BEGIN;

CREATE TABLE matches (
    game_id bigint NOT NULL,
    game_start_timestamp TIMESTAMPTZ NOT NULL,
    game_duration smallint NOT NULL,
    platform_name TEXT NOT NULL,
    game_version TEXT NOT NULL,
    end_of_game_result TEXT NOT NULL,
    match_id text NOT NULL REFERENCES match_ids(match_id),
    PRIMARY KEY (platform_name, game_id),
    FOREIGN KEY (platform_name) REFERENCES platforms(platform_name)
);

CREATE TYPE team_enum AS ENUM ('blue', 'red');

CREATE TABLE teams (
    game_id BIGINT NOT NULL,
    team_id team_enum NOT NULL,
    ---
    feats_epic_monster_state SMALLINT NOT NULL,
    feats_first_blood_state SMALLINT NOT NULL,
    feats_first_turret_state SMALLINT NOT NULL,
    --
    atakhan_kills SMALLINT NOT NULL,
    baron_kills SMALLINT NOT NULL,
    champion_kills SMALLINT NOT NULL,
    dragon_kills SMALLINT NOT NULL,
    horde_kills SMALLINT NOT NULL,
    inhibitor_kills SMALLINT NOT NULL,
    rift_herald_kills SMALLINT NOT NULL,
    tower_kills SMALLINT NOT NULL,
    atakhan_first BOOLEAN NOT NULL,
    baron_first BOOLEAN NOT NULL,
    champion_first BOOLEAN NOT NULL,
    dragon_first BOOLEAN NOT NULL,
    horde_first BOOLEAN NOT NULL,
    inhibitor_first BOOLEAN NOT NULL,
    rift_herald_first BOOLEAN NOT NULL,
    tower_first BOOLEAN NOT NULL,
    --
    feats_claimed BOOLEAN NOT NULL,
    win BOOLEAN NOT NULL,
    game_ended_in_surrender BOOLEAN NOT NULL,
    had_afk_teammate BOOLEAN NOT NULL,
    perfect_dragon_souls_taken BOOLEAN NOT NULL,
    --
    platform_name TEXT NOT NULL,
    PRIMARY KEY (platform_name, game_id, team_id),
    FOREIGN KEY (platform_name, game_id) REFERENCES matches(platform_name, game_id) ON DELETE CASCADE
);

CREATE TABLE team_bans (
    game_id BIGINT NOT NULL,
    team_id team_enum NOT NULL,
    pick_turn SMALLINT NOT NULL,
    champion_id SMALLINT REFERENCES champions(champion_id),
    platform_name TEXT NOT NULL,
    PRIMARY KEY (platform_name, game_id, team_id, pick_turn),
    FOREIGN KEY (platform_name, game_id, team_id) REFERENCES teams(platform_name, game_id, team_id) ON DELETE CASCADE
);

CREATE TYPE team_position_enum AS ENUM (
    'top',
    'jungle',
    'middle',
    'bottom',
    'utility'
);

CREATE TABLE match_participants (
    game_id BIGINT NOT NULL,
    team_id team_enum NOT NULL,
    team_position team_position_enum NOT NULL,
    participant_id SMALLINT NOT NULL,
    champion_id SMALLINT NOT NULL REFERENCES champions(champion_id),
    summoner1_id SMALLINT REFERENCES summoners(summoner_id),
    summoner2_id SMALLINT REFERENCES summoners(summoner_id),
    platform_name TEXT NOT NULL,
    PRIMARY KEY (platform_name, game_id, participant_id),
    FOREIGN KEY (platform_name, game_id, team_id) REFERENCES teams(platform_name, game_id, team_id) ON DELETE CASCADE
);

CREATE TABLE participant_stats (
    game_id BIGINT NOT NULL,
    champ_experience INT NOT NULL,
    damage_dealt_to_buildings INT NOT NULL,
    damage_dealt_to_objectives INT NOT NULL,
    damage_dealt_to_turrets INT NOT NULL,
    damage_self_mitigated INT NOT NULL,
    largest_critical_strike INT NOT NULL,
    magic_damage_dealt INT NOT NULL,
    magic_damage_dealt_to_champions INT NOT NULL,
    magic_damage_taken INT NOT NULL,
    physical_damage_dealt INT NOT NULL,
    physical_damage_dealt_to_champions INT NOT NULL,
    physical_damage_taken INT NOT NULL,
    total_damage_dealt INT NOT NULL,
    total_damage_dealt_to_champions INT NOT NULL,
    total_damage_shielded_on_teammates INT NOT NULL,
    total_damage_taken INT NOT NULL,
    true_damage_dealt INT NOT NULL,
    true_damage_dealt_to_champions INT NOT NULL,
    true_damage_taken INT NOT NULL,
    time_ccing_others INT NOT NULL,
    total_time_cc_dealt INT NOT NULL,
    total_heal INT NOT NULL,
    total_heals_on_teammates INT NOT NULL,
    total_units_healed INT NOT NULL,
    gold_earned INT NOT NULL,
    gold_spent INT NOT NULL,
    item0 int,
    item1 int,
    item2 int,
    item3 int,
    item4 int,
    item5 int,
    item6 int,
    participant_id SMALLINT NOT NULL,
    champion_transform SMALLINT NOT NULL,
    champ_level SMALLINT NOT NULL,
    kills SMALLINT NOT NULL,
    killing_sprees SMALLINT NOT NULL,
    largest_killing_spree SMALLINT NOT NULL,
    double_kills SMALLINT NOT NULL,
    triple_kills SMALLINT NOT NULL,
    quadra_kills SMALLINT NOT NULL,
    penta_kills SMALLINT NOT NULL,
    largest_multi_kill SMALLINT NOT NULL,
    bounty_level SMALLINT NOT NULL,
    deaths SMALLINT NOT NULL,
    longest_time_spent_living SMALLINT NOT NULL,
    total_time_spent_dead SMALLINT NOT NULL,
    assists SMALLINT NOT NULL,
    spell1_casts SMALLINT NOT NULL,
    spell2_casts SMALLINT NOT NULL,
    spell3_casts SMALLINT NOT NULL,
    spell4_casts SMALLINT NOT NULL,
    summoner1_casts SMALLINT NOT NULL,
    summoner2_casts SMALLINT NOT NULL,
    detector_wards_placed SMALLINT NOT NULL,
    wards_placed SMALLINT NOT NULL,
    wards_killed SMALLINT NOT NULL,
    vision_score SMALLINT NOT NULL,
    inhibitor_kills SMALLINT NOT NULL,
    inhibitor_takedowns SMALLINT NOT NULL,
    inhibitors_lost SMALLINT NOT NULL,
    turrets_lost SMALLINT NOT NULL,
    turret_takedowns SMALLINT NOT NULL,
    turret_kills SMALLINT NOT NULL,
    all_in_pings SMALLINT NOT NULL,
    assist_me_pings SMALLINT NOT NULL,
    command_pings SMALLINT NOT NULL,
    enemy_missing_pings SMALLINT NOT NULL,
    enemy_vision_pings SMALLINT NOT NULL,
    hold_pings SMALLINT NOT NULL,
    get_back_pings SMALLINT NOT NULL,
    need_vision_pings SMALLINT NOT NULL,
    on_my_way_pings SMALLINT NOT NULL,
    push_pings SMALLINT NOT NULL,
    vision_cleared_pings SMALLINT NOT NULL,
    dragon_kills SMALLINT NOT NULL,
    baron_kills SMALLINT NOT NULL,
    objectives_stolen SMALLINT NOT NULL,
    objectives_stolen_assists SMALLINT NOT NULL,
    total_ally_jungle_minions_killed SMALLINT NOT NULL,
    total_enemy_jungle_minions_killed SMALLINT NOT NULL,
    neutral_minions_killed SMALLINT NOT NULL,
    total_minions_killed SMALLINT NOT NULL,
    consumables_purchased SMALLINT NOT NULL,
    first_blood_kill BOOLEAN NOT NULL,
    first_blood_assist BOOLEAN NOT NULL,
    first_tower_kill BOOLEAN NOT NULL,
    first_tower_assist BOOLEAN NOT NULL,
    platform_name TEXT NOT NULL,
    PRIMARY KEY (platform_name, game_id, participant_id),
    FOREIGN KEY (platform_name, game_id, participant_id) REFERENCES match_participants (platform_name, game_id, participant_id) ON DELETE CASCADE
);

CREATE TABLE participant_challenges (
    game_id BIGINT NOT NULL,
    bounty_gold INT NOT NULL,
    effective_heal_and_shielding INT NOT NULL,
    kda REAL NOT NULL,
    kill_participation REAL NOT NULL,
    damage_per_minute REAL NOT NULL,
    damage_taken_on_team_pct REAL NOT NULL,
    team_damage_pct REAL NOT NULL,
    control_ward_time_coverage_in_river_or_enemy_half REAL NOT NULL,
    vision_score_advantage_lane_opponent REAL NOT NULL,
    vision_score_per_minute REAL NOT NULL,
    more_enemy_jungle_than_opponent REAL,
    gold_per_minute REAL NOT NULL,
    participant_id SMALLINT NOT NULL,
    max_level_lead_lane_opponent SMALLINT NOT NULL,
    jungler_kills_early_jungle SMALLINT NOT NULL,
    kills_on_laners_early_jungle_as_jungler SMALLINT NOT NULL,
    takedowns_first_25_minutes SMALLINT NOT NULL,
    aces_before_15_minutes SMALLINT NOT NULL,
    buffs_stolen SMALLINT NOT NULL,
    dodge_skill_shots_small_window SMALLINT NOT NULL,
    flawless_aces SMALLINT NOT NULL,
    kill_after_hidden_with_ally SMALLINT NOT NULL,
    kills_near_enemy_turret SMALLINT NOT NULL,
    kills_on_other_lanes_early_jungle_as_laner SMALLINT NOT NULL,
    kills_under_own_turret SMALLINT NOT NULL,
    kills_with_help_from_epic_monster SMALLINT NOT NULL,
    multikills_after_aggressive_flash SMALLINT NOT NULL,
    took_large_damage_survived SMALLINT NOT NULL,
    takedowns_before_jungle_minion_spawn SMALLINT NOT NULL,
    takedowns_after_gaining_level_advantage SMALLINT NOT NULL,
    takedown_on_first_turret SMALLINT NOT NULL,
    solo_kills SMALLINT NOT NULL,
    skillshots_dodged SMALLINT NOT NULL,
    save_ally_from_death SMALLINT NOT NULL,
    quick_solo_kills SMALLINT NOT NULL,
    pick_kill_with_ally SMALLINT NOT NULL,
    outnumbered_kills SMALLINT NOT NULL,
    enemy_champion_immobilizations SMALLINT NOT NULL,
    immobilize_and_kill_with_ally SMALLINT NOT NULL,
    knock_enemy_into_team_and_kill SMALLINT NOT NULL,
    land_skill_shots_early_game SMALLINT NOT NULL,
    skillshots_hit SMALLINT NOT NULL,
    ward_takedowns_before_20m SMALLINT NOT NULL,
    ward_takedowns SMALLINT NOT NULL,
    wards_guarded SMALLINT NOT NULL,
    solo_turrets_late_game SMALLINT NOT NULL,
    k_turrets_destroyed_before_plates_fall SMALLINT NOT NULL,
    turrets_taken_with_rift_herald SMALLINT NOT NULL,
    turret_plates_taken SMALLINT NOT NULL,
    quick_first_turret SMALLINT NOT NULL,
    multi_turret_rift_herald_count SMALLINT NOT NULL,
    max_cs_advantage_on_lane_opponent SMALLINT NOT NULL,
    void_monster_kill SMALLINT NOT NULL,
    allied_jungle_monster_kills SMALLINT NOT NULL,
    elder_dragon_kills_with_opposing_soul SMALLINT NOT NULL,
    enemy_jungle_monster_kills SMALLINT NOT NULL,
    epic_monster_steals SMALLINT NOT NULL,
    initial_buff_count SMALLINT NOT NULL,
    initial_crab_count SMALLINT NOT NULL,
    jungle_cs_before_10_minutes SMALLINT NOT NULL,
    lane_minions_first_10_minutes SMALLINT NOT NULL,
    rift_herald_takedowns SMALLINT NOT NULL,
    solo_baron_kills SMALLINT NOT NULL,
    was_afk BOOLEAN NOT NULL,
    platform_name TEXT NOT NULL,
    PRIMARY KEY (platform_name, game_id, participant_id),
    FOREIGN KEY (platform_name, game_id, participant_id) REFERENCES match_participants (platform_name, game_id, participant_id) ON DELETE CASCADE
);

CREATE TYPE perk_style AS ENUM (
    'precision',
    'domination',
    'sorcery',
    'resolve',
    'inspiration'
);

CREATE TABLE participant_perks (
    game_id BIGINT NOT NULL,
    primary_perk_style perk_style,
    secondary_perk_style perk_style,
    primary_perk1_var1 int,
    primary_perk1_var2 int,
    primary_perk1_var3 int,
    primary_perk2_var1 int,
    primary_perk2_var2 int,
    primary_perk2_var3 int,
    primary_perk3_var1 int,
    primary_perk3_var2 int,
    primary_perk3_var3 int,
    primary_perk4_var1 int,
    primary_perk4_var2 int,
    primary_perk4_var3 int,
    secondary_perk1_var1 int,
    secondary_perk1_var2 int,
    secondary_perk1_var3 int,
    secondary_perk2_var1 int,
    secondary_perk2_var2 int,
    secondary_perk2_var3 int,
    participant_id SMALLINT NOT NULL,
    defense_perk_id SMALLINT REFERENCES perks(perk_id),
    flex_perk_id SMALLINT REFERENCES perks(perk_id),
    offense_perk_id SMALLINT REFERENCES perks(perk_id),
    primary_perk1_id smallint REFERENCES perks(perk_id),
    primary_perk2_id smallint REFERENCES perks(perk_id),
    primary_perk3_id smallint REFERENCES perks(perk_id),
    primary_perk4_id smallint REFERENCES perks(perk_id),
    secondary_perk1_id smallint REFERENCES perks(perk_id),
    secondary_perk2_id smallint REFERENCES perks(perk_id),
    platform_name TEXT NOT NULL,
    PRIMARY KEY (platform_name, game_id, participant_id),
    FOREIGN KEY (platform_name, game_id, participant_id) REFERENCES match_participants (platform_name, game_id, participant_id) ON DELETE CASCADE
);

COMMIT;
